### ISSUE TITLE
Build badge reports failing even though master is green.

### ISSUE THREAD

**Issue by GeorgeLyon** [airbnb/ResilientDecoding#12]
I think this may be because it doesn't disambiguate between failures in master and failures in PR branches?

**Comment by dfed** [comment]
@GeorgeLyon it looks good to me?
![1CC54C1E-E82A-4A8B-9AEA-48E52B2C5A4C](https://user-images.githubusercontent.com/139364/79080028-6bf86b00-7cc7-11ea-9d84-0d65bc22f260.png)

Maybe try clearing your browser cache? I’m closing, but feel free to re-open.

**Comment by GeorgeLyon** [comment]
I think this might be because I pushed my branch and that second CI pass succeeded. I'll keep an eye on this.

**Comment by dfed** [comment]
We can specify `master`, but it should be the default per https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
