### ISSUE TITLE
Missing Initializer

### ISSUE THREAD

**Issue by hanshamm** [airbnb/ResilientDecoding#31]
I would hardly recommend adding the wrappedValue initializer so that somone can construct an array without adding Resilient wrapped constructors
```
 public init(wrappedValue: Value) {
    self.wrappedValue = wrappedValue
    self.outcome = .decodedSuccessfully
  }
```

Example without this initializer:
```
struct DemoStruct: Decodable {
    @Resilient var array: [Int]
    @Resilient var value: Int?
    @Resilient var text: String?
    static let defaultValue = DemoStruct(array: [], value: nil, text: nil) // see errors 1-3 below
}
```
1) error: 'nil' is not compatible with expected argument type 'Resilient<Int?>'
2) error: 'nil' is not compatible with expected argument type 'Resilient<String?>'
3) error: Cannot convert value of type '[Any]' to expected argument type 'Resilient<[Int]>'

With the above initialiser the example just works fine. Please consider adding my suggestion as soon as possible ;-)

**Comment by GeorgeLyon** [comment]
This is a highly reasonable request. If you provide a PR, we'd be happy to merge it.
